layout_spectrum: 0.8064163625240326
typography_spectrum: 0.8463732739910483
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.07918401504866779
  lightness: 0.8096097551751882
  saturation: 0.12475519208237529
  rhythmicContrast: 0.29577046376653016
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: timeless
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Central Question
    id: 138d6cbf-afc7-426d-9bf0-1f52c1152a8a
    type: content
favicon: null
title: Vision Quest
description: Bringing a Most Important Question To Mother Earth
purpose: []
