name: timeless
favicon: null
layout_spectrum: 0.9774198560044169
typography_spectrum: 0.8672734443098307
title: Vision Quest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a1010'
    - '#ffffff'
    - '#4b4948'
    - '#a1978a'
    - '#c2b7a3'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
