typography_spectrum: 0.8672734443098307
color:
  brandColors:
    - '#0a1010'
    - '#ffffff'
    - '#4b4948'
    - '#a1978a'
    - '#c2b7a3'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9774198560044169
analytics:
  google: null
  facebook: null
  twitter: null
name: timeless
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Central Question
    id: 138d6cbf-afc7-426d-9bf0-1f52c1152a8a
    type: content
favicon: null
title: Vision Quest
description: Bringing a Most Important Question To Mother Earth
purpose: []
